configuration:
  replicaCount: 1
  nameSpace: jobii
  tier: backend

image:
  repository: 955940554927.dkr.ecr.us-east-1.amazonaws.com/jobii-test-build
  tag: latest
  pullPolicy: Always

service:
  port: 80


container:
  # port: 8090
  port: 3000
  portName: port-client
  env:
    - name: PORT
      # value: 8090
      value: 3000
# secrets
  envValueFrom:
    enabled: true
    values:
      - name: mongo-secret-jobii-jobs
        nameKey: username
        envName: MONGO_USER
      - name: mongo-secret-jobii-jobs
        nameKey: password
        envName: MONGO_PASS
      - name: jobii-mongo-credentials
        nameKey: address.txt
        envName: MONGO_HOSTNAME

resources:
  enabled: false
  limits:
    cpu: "0.2"
    memory: 256Mi
  requests:
    cpu: "0.1"
    memory: 128Mi

probe:
  path: /health
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 1

  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 1

securityContext: 
  runAsUser: 10000
  runAsGroup: 10000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  privileged: false
